
export const ActionTypes = {
    CHAT_ADDLINE:           'CHAT_ADDLINE',
    SAVE_SETTINGS:          'SAVE_SETTINGS',
    CHAT_SEND_MESSAGE:      'CHAT_SEND_MESSAGE',
    CHAT_RECEIVE_MESSAGE:   'CHAT_RECEIVE_MESSAGE',
    RESET_TO_DEFAULTS:      'RESET_TO_DEFAULTS',
    CLEAR_UNREAD:           'CLEAR_UNREAD',
    IS_CONNECTED:           'IS_CONNECTED'
}
